INSERT INTO Fruit(name,season) VALUES ('Mango','Spring');
INSERT INTO Fruit(name,season) VALUES ('Strawberry','Spring');
INSERT INTO Fruit(name,season) VALUES ('Orange','Winter');
INSERT INTO Fruit(name,season) VALUES ('Lemon','Winter');
INSERT INTO Fruit(name,season) VALUES ('Blueberry','Summer');
INSERT INTO Fruit(name,season) VALUES ('Banana','Summer');
INSERT INTO Fruit(name,season) VALUES ('Watermelon','Summer');
INSERT INTO Fruit(name,season) VALUES ('Apple','Fall');
INSERT INTO Fruit(name,season) VALUES ('Pear','Fall');