kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: maria-pvclaim
  namespace: anasandbox-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem